---
- name: Detect RedHat flavor
  set_fact:
    pg_shortver: "{{ pg_version | replace('.', '') }}"
    rh_family: "{% if ansible_distribution == 'Fedora' %}fedora{% else %}redhat{% endif %}"
    rh_flavor: "{% if ansible_distribution == 'Fedora' %}fedora{% else %}rhel{% endif %}"
    rh_suffix: "{% if ansible_distribution == 'Scientific' %}sl{% else %}{{ ansible_distribution | lower }}{% endif %}"

- name: Check PGDG release
  yum:
    list: "pgdg-{{ rh_suffix }}{{ pg_shortver }}"
  register: rh_release

- name: Configure YUM repository
  yum_repository:
    name: pgdg-ansible
    description: Temporary repository installed by Ansible
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ pg_version }}/{{ rh_family }}/{{ rh_flavor }}-$releasever-$basearch
  when: "{{ rh_release.results | selectattr('yumstate', 'equalto', 'installed') | list | length == 0 }}"
