---
- name: Detect RedHat flavor
  set_fact:
    rh_flavor: "{% if ansible_distribution == 'Fedora' %}fedora{% else %}redhat{% endif %}"
    rh_repo: "{% if ansible_distribution == 'Scientific' %}sl{% else %}{{ ansible_distribution | lower }}{% endif %}"
    pg_shortver: "{{ pg_version | replace('.', '') }}"

- name: Configure YUM repository
  yum_repository:
    name: pgdg{{ pg_shortver }}
    file: pgdg-{{ pg_shortver }}-{{ rh_repo }}-delete
    description: PostgreSQL {{ pg_version }} $releasever - $basearch
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ pg_version }}/{{ rh_flavor }}/{{ rh_flavor }}-$releasever-$basearch
